'use client';
import {useEffect,useMemo,useState} from 'react';

const flows=['Exportações','Importações','Global'];
const freqs={mensal:'Mensal',trimestral:'Trimestral',semestral:'Semestral',anual:'Anual'};
const sections=['I — Animais vivos e produtos do reino animal','II — Produtos do reino vegetal','III — Gorduras e óleos','IV — Produtos alimentares, bebidas e tabaco','V — Produtos minerais','VI — Indústrias químicas','VII — Plásticos e borracha','VIII — Peles, couros e artigos','IX — Madeira e cortiça','X — Pastas de madeira, papel e cartão','XI — Matérias têxteis e obras','XII — Calçado, chapéus e semelhantes','XIII — Pedra, cimento, cerâmica e vidro','XIV — Pérolas, pedras e metais preciosos','XV — Metais comuns e obras','XVI — Máquinas e aparelhos','XVII — Material de transporte','XVIII — Instrumentos ópticos e de precisão','XIX — Armas e munições','XX — Mercadorias e produtos diversos','XXI — Objectos de arte e antiguidades'];
const dl='/downloads/';
const files=[
 ['Resultados recalculados','Excel','Indices_Comercio_Externo_Recalculados_2022_2025_Previsao_2026.xlsx'],
 ['Fontes públicas agregadas','Excel','Fontes_Publicas_Agregadas_ICE_2022_2025.xlsx'],
 ['Relatório técnico','PDF','Relatorio_Tecnico_Indices_Comercio_Externo_Recalculados_2022_2025_Previsao_2026.pdf'],
 ['Relatório editável','Word','Relatorio_Tecnico_Indices_Comercio_Externo_Recalculados_2022_2025_Previsao_2026.docx'],
 ['Apresentação','PDF','Apresentacao_Indices_Comercio_Externo_Recalculados_2022_2025_Previsao_2026.pdf'],
 ['Apresentação editável','PowerPoint','Apresentacao_Indices_Comercio_Externo_Recalculados_2022_2025_Previsao_2026.pptx']
];
const fmt=(n:number)=>n?.toLocaleString('pt-MZ',{minimumFractionDigits:2,maximumFractionDigits:2});

export default function Home(){
 const [data,setData]=useState<any>(); const [flow,setFlow]=useState('Global'); const [freq,setFreq]=useState('anual'); const [year,setYear]=useState(2025);
 useEffect(()=>{fetch('/data/results.json').then(r=>r.json()).then(setData)},[]);
 const rows=useMemo(()=>data?.results?.[freq]?.filter((r:any)=>freq==='anual'||r.year===year)??[],[data,freq,year]);
 const vals=rows.map((r:any)=>r[flow]?.index).filter((v:any)=>Number.isFinite(v)); const min=vals.length?Math.min(...vals):75,max=vals.length?Math.max(...vals):110;
 const pts=rows.map((r:any,i:number)=>{const v=r[flow]?.index;const x=rows.length===1?50:5+i*90/(rows.length-1);const y=88-(v-min)/(Math.max(1,max-min))*70;return `${x},${y}`}).join(' ');
 const forecast=data?.forecast_2026?.[flow];
 return <main>
  <header className="hero"><nav><div className="brand"><span className="seal">ME</span><span>Ministério da Economia<br/><b>República de Moçambique</b></span></div><a href="#downloads">Documentos ↓</a></nav><div className="heroGrid"><div><p className="eyebrow">CENTRO DE DADOS · BASE 2022=100</p><h1>Índices do Comércio<br/>Externo de Moçambique</h1><p className="lead">Exportações, importações e índice global recalculados numa única plataforma, com resultados mensais, trimestrais, semestrais e anuais.</p><div className="notice">Cobertura observada: Jan 2022–Set 2025 · Previsão indicativa: 2026</div></div><div className="heroStats"><span>398</span><p>posições SH8 no cabaz fixo</p><span>71 913</span><p>agregados públicos mês × SH8</p><span>4</span><p>periodicidades analíticas</p></div></div></header>
  <section className="wrap" id="centro"><div className="sectionHead"><div><p className="eyebrow dark">EXPLORADOR INTERACTIVO</p><h2>Centro de dados</h2></div><p>Seleccione o fluxo e a periodicidade. Os valores de 2025 correspondem a janeiro–setembro.</p></div>
   <div className="controls"><div><label>Fluxo</label><div className="seg">{flows.map(f=><button key={f} className={flow===f?'active':''} onClick={()=>setFlow(f)}>{f}</button>)}</div></div><div><label>Periodicidade</label><select value={freq} onChange={e=>setFreq(e.target.value)}>{Object.entries(freqs).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{freq!=='anual'&&<div><label>Ano</label><select value={year} onChange={e=>setYear(+e.target.value)}>{[2022,2023,2024,2025].map(y=><option key={y}>{y}</option>)}</select></div>}</div>
   <div className="dashboard"><article className="chartCard"><div className="cardTitle"><h3>{flow} · {freqs[freq as keyof typeof freqs]}</h3><span>Índice</span></div>{rows.length?<><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="chart"><line x1="5" y1="50" x2="95" y2="50"/><polyline points={pts}/>{rows.map((r:any,i:number)=>{const [x,y]=pts.split(' ')[i].split(',');return <circle key={i} cx={x} cy={y} r="1.6"/>})}</svg><div className="xlabels">{rows.map((r:any)=><span key={r.period}>{r.period.replace(String(r.year),'').trim()||r.period}</span>)}</div></>:<p>Sem observações para esta selecção.</p>}</article>
    <aside className="forecast"><p className="eyebrow">CENÁRIO 2026</p><strong>{forecast?fmt(forecast.point):'—'}</strong><p>Intervalo indicativo<br/><b>{forecast?fmt(forecast.lower_scenario):'—'}–{forecast?fmt(forecast.upper_scenario):'—'}</b></p><small>Tendência linear OLS 2022–2025. Como 2025 é parcial, não constitui previsão oficial.</small></aside></div>
   <div className="tableWrap"><table><thead><tr><th>Período</th><th>Exportações</th><th>Importações</th><th>Global</th></tr></thead><tbody>{rows.map((r:any)=><tr key={r.period}><td>{r.period}</td>{flows.map(f=><td key={f} className={flow===f?'focus':''}>{fmt(r[f]?.index)}</td>)}</tr>)}</tbody></table></div>
  </section>
  <section className="bands"><div className="wrap"><p className="eyebrow">RESULTADOS ANUAIS</p><h2>As três leituras, lado a lado</h2><div className="annualGrid">{flows.map(f=><article key={f}><h3>{f}</h3>{data?.annual_series?.[f]&&Object.entries(data.annual_series[f]).map(([y,v]:any)=><div key={y}><span>{y}{y==='2025'?'*':''}</span><b>{fmt(v)}</b></div>)}</article>)}</div><small>* 2025: janeiro–setembro.</small></div></section>
  <section className="wrap groups"><div className="sectionHead"><div><p className="eyebrow dark">ESTRUTURA DO COMÉRCIO</p><h2>Os 21 grupos de produtos</h2></div><p>Resultados anuais por secção do Sistema Harmonizado para exportações e importações.</p></div><div className="groupFlow"><button className={flow==='Exportações'?'active':''} onClick={()=>setFlow('Exportações')}>Exportações</button><button className={flow==='Importações'?'active':''} onClick={()=>setFlow('Importações')}>Importações</button></div><div className="groupGrid">{sections.map((name,i)=>{const key=['I','II','III','IV','V','VI','VII','VIII','IX','X','XI','XII','XIII','XIV','XV','XVI','XVII','XVIII','XIX','XX','XXI'][i];const f=flow==='Global'?'Exportações':flow;const v=data?.section_results?.[f]?.[key];return <article key={key}><span>{key}</span><h3>{name.split(' — ')[1]}</h3><p>2025*: <b>{v?fmt(v['2025']):'—'}</b></p></article>})}</div></section>
  <section className="method"><div className="wrap methodGrid"><div><p className="eyebrow">METODOLOGIA</p><h2>Cabaz fixo, controlo de qualidade e rastreabilidade</h2><p>IVU com base 2022=100; agregação SH8; unidades convertíveis em quilogramas; filtros mínimos de USD 1.000 e 100 kg; testes de continuidade, dispersão e outliers; ponderação pelo valor corrente. O índice global combina os fluxos com pesos de 2022.</p></div><ol><li>Preparar e validar os registos</li><li>Construir o cabaz fixo de 2022</li><li>Calcular IVU por SH8 e período</li><li>Ponderar exportações e importações</li><li>Combinar no índice global</li></ol></div></section>
  <section className="wrap downloads" id="downloads"><div className="sectionHead"><div><p className="eyebrow dark">ANEXOS E FONTES</p><h2>Documentos para consulta</h2></div><p>As fontes públicas estão agregadas para preservar NUIT, nomes e identificadores empresariais.</p></div><div className="downloadGrid">{files.map(([title,type,file])=><a key={file} href={dl+file} download><span>{type}</span><h3>{title}</h3><b>Descarregar ↓</b></a>)}</div></section>
  <footer><div className="wrap"><b>Índices do Comércio Externo de Moçambique</b><span>Versão recalculada · Agosto 2026</span></div></footer>
 </main>
}
