"use client";
import {useMemo,useState} from "react";
import dataset from "../data/scenarios.json";
type GeoRow={flow:string;year:number;continent:string;country:string;lat:number;lon:number;value:number};
type ProvinceRow={flow:string;year:number;province:string;value:number};
const fmt=(n:number)=>n.toLocaleString("pt-PT",{maximumFractionDigits:0});
const continentName=(v:string)=>v==="Oceania"?"Oceânia":v;
const validContinent=(v:string)=>!['#N/A','0','Não classificado','Outros Países Não Classificados','Zona Neutra'].includes(v);
const provinceName=(v:string)=>v.replace('MAPUTO PROVÍNCIA','MAPUTO PROV').replace('ZAMBÉZIA','ZAMBEZIA');
const provincePoints:Record<string,[number,number]>={NIASSA:[206,58],'CABO DELGADO':[292,72],NAMPULA:[270,174],ZAMBEZIA:[230,274],TETE:[135,260],MANICA:[135,368],SOFALA:[207,382],INHAMBANE:[205,494],GAZA:[157,570],'MAPUTO PROV':[125,625],'MAPUTO CIDADE':[105,652]};
export default function GeoTrade(){
 const[year,setYear]=useState(2025),[continent,setContinent]=useState(''),[country,setCountry]=useState('');
 const geo=dataset.geography as GeoRow[],provs=dataset.provinces as ProvinceRow[];
 const continents=useMemo(()=>Array.from(new Set(geo.map(r=>continentName(r.continent)).filter(validContinent))).sort((a,b)=>a.localeCompare(b,'pt')),[geo]);
 const countries=useMemo(()=>Array.from(new Set(geo.filter(r=>!continent||continentName(r.continent)===continent).map(r=>r.country).filter(v=>v&&v!=='#N/A'&&v!=='Não identificado'))).sort((a,b)=>a.localeCompare(b,'pt')),[geo,continent]);
 const partner=useMemo(()=>{const m=new Map<string,{country:string,continent:string,lat:number,lon:number,exports:number,imports:number}>();geo.filter(r=>r.year===year&&validContinent(continentName(r.continent))).forEach(r=>{const old=m.get(r.country)||{country:r.country,continent:continentName(r.continent),lat:r.lat,lon:r.lon,exports:0,imports:0};old[r.flow==='EXP'?'exports':'imports']+=r.value;if(r.lat||r.lon){old.lat=r.lat;old.lon=r.lon}m.set(r.country,old)});return Array.from(m.values()).filter(r=>(!continent||r.continent===continent)&&(!country||r.country===country)).map(r=>({...r,balance:r.exports-r.imports})).sort((a,b)=>b.exports+b.imports-a.exports-a.imports)},[geo,year,continent,country]);
 const max=Math.max(1,...partner.map(r=>r.exports+r.imports)),totals=partner.reduce((a,r)=>({exports:a.exports+r.exports,imports:a.imports+r.imports}),{exports:0,imports:0});
 const provinceData=useMemo(()=>{const m=new Map<string,{province:string,exports:number,imports:number}>();provs.filter(r=>r.year===year).forEach(r=>{const n=provinceName(r.province),o=m.get(n)||{province:n,exports:0,imports:0};o[r.flow==='EXP'?'exports':'imports']+=r.value;m.set(n,o)});return Array.from(m.values()).map(r=>({...r,balance:r.exports-r.imports}))},[provs,year]);
 const pmax=Math.max(1,...provinceData.map(r=>r.exports+r.imports));
 return <section className="geo-section"><div className="geo-head"><div><span>GEOGRAFIA DO COMÉRCIO</span><h2>Parceiros comerciais e províncias</h2><p>Seleccione primeiro o continente e depois o país. Os círculos representam o valor total de exportações e importações, em mil USD.</p></div><label>Ano<select value={year} onChange={e=>setYear(+e.target.value)}>{[2022,2023,2024,2025].map(y=><option key={y}>{y}</option>)}</select></label></div>
 <div className="geo-filters"><label><b>1</b> Continente<select value={continent} onChange={e=>{setContinent(e.target.value);setCountry('')}}><option value="">Seleccione o continente</option>{continents.map(c=><option key={c}>{c}</option>)}</select></label><label><b>2</b> País<select value={country} disabled={!continent} onChange={e=>setCountry(e.target.value)}><option value="">Todos os países</option>{countries.map(c=><option key={c}>{c}</option>)}</select></label><article><small>EXPORTAÇÕES</small><strong>{fmt(totals.exports)}</strong></article><article><small>IMPORTAÇÕES</small><strong>{fmt(totals.imports)}</strong></article><article className={totals.exports-totals.imports<0?'deficit':'surplus'}><small>BALANÇA</small><strong>{fmt(totals.exports-totals.imports)}</strong></article></div>
 <div className="maps-grid"><article className="map-card"><div className="map-title"><div><span>MAPA MUNDO</span><h3>{country||continent||'Todos os parceiros'}</h3></div><small>Tamanho = Exportações + Importações</small></div><svg viewBox="0 0 960 450" className="world-map" role="img" aria-label="Mapa mundial dos parceiros comerciais"><g className="land"><path d="M55 86l80-42 120 15 44 57-34 57-78 8-27 72-62-41-43-70z"/><path d="M265 245l45 42 15 95-42 54-35-95z"/><path d="M410 75l68-36 105 15 29 42-49 37-68-9-43 36-59-38z"/><path d="M470 165l85-19 64 57-20 122-58 72-48-93z"/><path d="M585 62l142-34 138 67-12 77-82 22-58 74-91-26-42-80z"/><path d="M756 303l76-23 71 45-22 62-89 6-47-48z"/></g>{partner.filter(r=>Number.isFinite(r.lat+r.lon)&&(r.lat||r.lon)).map(r=>{const cx=(r.lon+180)/360*960,cy=(90-r.lat)/180*450,rad=4+Math.sqrt((r.exports+r.imports)/max)*22;return <g key={r.country} className="map-point"><circle cx={cx} cy={cy} r={rad}/><title>{r.country}: Exp. {fmt(r.exports)} · Imp. {fmt(r.imports)} · Saldo {fmt(r.balance)} mil USD</title></g>})}</svg><div className="partner-table"><table><thead><tr><th>País</th><th>Exportações</th><th>Importações</th><th>Saldo</th></tr></thead><tbody>{partner.slice(0,8).map(r=><tr key={r.country}><td>{r.country}</td><td>{fmt(r.exports)}</td><td>{fmt(r.imports)}</td><td className={r.balance<0?'negative':'positive'}>{fmt(r.balance)}</td></tr>)}</tbody></table></div></article>
 <article className="map-card moz-card"><div className="map-title"><div><span>MAPA DE MOÇAMBIQUE</span><h3>Comércio por província</h3></div><small>{year} · mil USD</small></div><div className="moz-layout"><svg viewBox="0 0 360 680" className="moz-map" role="img" aria-label="Mapa de Moçambique por província"><path className="moz-land" d="M188 18l82 26 50 57-14 95-42 95-24 103 21 85-36 82-39 97-56 15-34-34 23-75 31-72 2-91-43-72 20-84 29-78z"/>{provinceData.map(r=>{const p=provincePoints[r.province];if(!p)return null;const rad=7+Math.sqrt((r.exports+r.imports)/pmax)*22;return <g key={r.province} className="province-point"><circle cx={p[0]} cy={p[1]} r={rad}/><text x={p[0]+rad+4} y={p[1]+4}>{r.province.replace('MAPUTO PROV','MAPUTO')}</text><title>{r.province}: Exp. {fmt(r.exports)} · Imp. {fmt(r.imports)} · Saldo {fmt(r.balance)} mil USD</title></g>})}</svg><div className="province-list">{provinceData.sort((a,b)=>b.exports+b.imports-a.exports-a.imports).map(r=><div key={r.province}><b>{r.province}</b><span>Exp. {fmt(r.exports)}</span><span>Imp. {fmt(r.imports)}</span></div>)}</div></div></article></div><p className="geo-note">Fonte geográfica: campos Continente, Country_name_pt, Latitude, Longitude e PROVÍNCIA dos ficheiros aduaneiros. A província representa o local registado na declaração, não necessariamente a origem produtiva ou o destino final da mercadoria.</p></section>
}
