"use client";
import { useMemo, useState } from "react";
import ComparisonPanel from "./comparison-panel";
import AnalyticsExpansion from "./analytics-expansion";
import GeoTrade from "./geo-trade";
import DataManagement from "./data-management";
type Annual={flow:string;year:number;section?:number;index:number|null;coverage:number;matched:number;fallback_sh4:number};
type Monthly={flow:string;year:number;month:number;section?:number;raw:number|null;index:number|null;coverage:number};
type Periodic={flow:string;year:number;section?:number;month?:number;period?:number;index:number|null;coverage:number};
type Section={id:number;roman:string;name:string};
type Dataset={meta:Record<string,unknown>;sections:Section[];annual:Annual[];monthly:Monthly[];quarterly:Periodic[];semester:Periodic[]};
const fmt=(n:number|null|undefined,d=1)=>n==null?"—":n.toLocaleString("pt-PT",{minimumFractionDigits:d,maximumFractionDigits:d});
const months=["Jan","Fev","Mar","Abr","Mai","Jun","Jul","Ago","Set","Out","Nov","Dez"];
function LineChart({points}:{points:{label:string,value:number|null}[]}){const valid=points.filter(p=>p.value!=null) as {label:string,value:number}[];const max=Math.max(120,...valid.map(p=>p.value)),min=Math.min(60,...valid.map(p=>p.value));const xy=points.map((p,i)=>({x:32+i*(636/Math.max(1,points.length-1)),y:p.value==null?null:205-(p.value-min)/(max-min||1)*150,...p}));const path=xy.filter(p=>p.y!=null).map((p,i)=>`${i?"L":"M"}${p.x},${p.y}`).join(" ");return <div className="chart-wrap"><svg viewBox="0 0 700 245" role="img" aria-label="Evolução do índice">{[0,1,2,3].map(i=><line key={i} x1="32" x2="668" y1={55+i*50} y2={55+i*50} className="gridline"/>)}<line x1="32" x2="668" y1={205-(100-min)/(max-min||1)*150} y2={205-(100-min)/(max-min||1)*150} className="baseline"/><path d={path} className="line"/>{xy.map((p,i)=>p.y==null?null:<g key={i}><circle cx={p.x} cy={p.y} r="4.5"/><text x={p.x} y={(p.y as number)-12}>{fmt(p.value)}</text><text x={p.x} y="230" className="axis">{p.label}</text></g>)}</svg></div>}
export default function Portal({data}:{data:Dataset}){const[flow,setFlow]=useState("EXP"),[period,setPeriod]=useState("annual"),[year,setYear]=useState(2025),[section,setSection]=useState(0),[query,setQuery]=useState("");const selected=useMemo(()=>data.annual.find(x=>x.flow===flow&&x.year===year&&(section?x.section===section:x.section==null)),[data,flow,year,section]);const points=period==="annual"?[2022,2023,2024,2025].map(y=>({label:String(y),value:data.annual.find(x=>x.flow===flow&&x.year===y&&(section?x.section===section:x.section==null))?.index??null})):[1,2,3,4,5,6,7,8,9,10,11,12].map(m=>({label:months[m-1],value:data.monthly.find(x=>x.flow===flow&&x.year===year&&x.month===m)?.index??null}));const cards=data.sections.filter(s=>s.name.toLowerCase().includes(query.toLowerCase()));return <main>
<nav className="topbar"><a className="brand" href="#inicio"><span>ME</span><div><b>REPÚBLICA DE MOÇAMBIQUE</b><small>MINISTÉRIO DA ECONOMIA · DNCE</small></div></a><div className="navlinks"><a href="#dados">Centro de Dados</a><a href="#grupos">21 Grupos</a><a href="#metodologia">Metodologia</a><a href="#gestao">Área reservada</a></div><a className="navcta" href="#dados">Explorar dados ↗</a></nav>
<header id="inicio" className="hero"><div className="eyebrow">ESTATÍSTICAS DO COMÉRCIO EXTERNO · NOVA SÉRIE</div><h1>Índices do <em>Comércio Externo</em><br/>de Moçambique</h1><p>Uma plataforma oficial para compreender preços implícitos, quantidades e valores das exportações e importações, com elevada representatividade e base 2022 = 100.</p><div className="hero-actions"><a href="#dados">Explorar resultados ↗</a><a href="#metodologia" className="secondary">Conhecer a metodologia</a></div><div className="status"><i/> Série preliminar calculada a partir de 1.623.636 registos</div></header>
<section className="stats"><article><small>ANO-BASE</small><strong>2022 = 100</strong><span>12 meses completos</span></article><article><small>COBERTURA-ALVO</small><strong>≥ 90%</strong><span>do valor comercial</span></article><article><small>CLASSIFICAÇÃO</small><strong>SH8 + SH4</strong><span>21 Secções SH</span></article><article><small>CONTROLO</small><strong>25–300</strong><span>limites elementares</span></article></section>
<section className="global-strip"><div><small>ÍNDICE GLOBAL ANUAL</small><b>Exportações + Importações</b></div>{[2022,2023,2024,2025].map(y=>{const r=data.annual.find(x=>x.flow==="GBL"&&x.year===y&&x.section==null);return <article key={y}><span>{y}</span><strong>{fmt(r?.index,2)}</strong><small>{fmt(r?.coverage,1)}% de cobertura</small></article>})}</section>
<section id="dados" className="section light"><div className="section-head"><div><span className="kicker">EXPLORADOR INTERACTIVO</span><h2>Centro de Dados</h2><p>Filtre o fluxo, a periodicidade, o ano e a Secção do Sistema Harmonizado.</p></div><button className="download">↓ Descarregar resultados</button></div><div className="filters"><div><label>Fluxo</label><div className="segmented"><button className={flow==="EXP"?"active":""} onClick={()=>setFlow("EXP")}>Exportações</button><button className={flow==="IMP"?"active":""} onClick={()=>setFlow("IMP")}>Importações</button></div></div><div><label>Periodicidade</label><select value={period} onChange={e=>setPeriod(e.target.value)}><option value="annual">Anual</option><option value="monthly">Mensal</option></select></div><div><label>Ano</label><select value={year} onChange={e=>setYear(+e.target.value)}>{[2022,2023,2024,2025].map(y=><option key={y}>{y}</option>)}</select></div><div><label>Grupo</label><select value={section} onChange={e=>setSection(+e.target.value)}><option value="0">Índice geral</option>{data.sections.map(s=><option key={s.id} value={s.id}>{s.roman} — {s.name}</option>)}</select></div></div><div className="viz-grid"><article className="chart-card"><div className="chart-title"><div><span>SÉRIE SELECCIONADA</span><h3>{section?data.sections[section-1].name:"Índice geral"} · {flow==="EXP"?"Exportações":"Importações"}</h3></div><b>{fmt(selected?.index,2)}</b></div><LineChart points={points}/></article><aside className="quality"><span>QUALIDADE DA SELECÇÃO</span><div className="gauge" style={{"--coverage":`${Math.min(100,selected?.coverage||0)*3.6}deg`} as React.CSSProperties}><b>{fmt(selected?.coverage)}%</b><small>cobertura</small></div><dl><div><dt>SH8 correspondentes</dt><dd>{selected?.matched||0}</dd></div><div><dt>Apoio por SH4</dt><dd>{selected?.fallback_sh4||0}</dd></div><div><dt>Unidades PST</dt><dd>Incluídas</dd></div></dl></aside></div></section>
<section id="grupos" className="section groups"><div className="section-head"><div><span className="kicker">SECÇÕES DO SISTEMA HARMONIZADO</span><h2>Os 21 grupos, todos visíveis</h2><p>O SH8 é o nível de referência; o SH4 actua como apoio quando melhora a representatividade.</p></div><input aria-label="Pesquisar grupo" placeholder="Pesquisar grupo…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="group-grid">{cards.map(s=>{const r=data.annual.find(x=>x.flow===flow&&x.year===year&&x.section===s.id);return <button key={s.id} onClick={()=>{setSection(s.id);document.querySelector("#dados")?.scrollIntoView({behavior:"smooth"})}}><span>{s.roman}</span><div><h3>{s.name}</h3><p>{flow==="EXP"?"Exportações":"Importações"} · {year}</p></div><strong>{fmt(r?.index,1)}</strong><small>{fmt(r?.coverage,0)}% cob.</small></button>})}</div></section>
<section id="metodologia" className="section methodology"><div><span className="kicker">METODOLOGIA E RASTREABILIDADE</span><h2>Representatividade sem perder rigor</h2><p>O cálculo preserva a metodologia do Índice de Valor Unitário, mas amplia o cabaz através da normalização segura de unidades e do apoio SH4. O valor em USD pode ser apresentado multiplicado por 1.000; a escala não altera o índice.</p><ol><li><b>01</b><span><strong>Validar e normalizar</strong>KG, gramas e variantes compatíveis são convertidas; litros, m², m³, energia e peças permanecem em famílias próprias.</span></li><li><b>02</b><span><strong>Calcular no SH8</strong>Valor unitário por SH8, fluxo, unidade e período, com 2022 como referência.</span></li><li><b>03</b><span><strong>Reforçar pelo SH4</strong>Quando não existe correspondência SH8, o SH4 auxilia sem misturar unidades incompatíveis.</span></li><li><b>04</b><span><strong>Controlar extremos</strong>Índices elementares limitados ao intervalo 25–300 e série mensal suavizada por mediana móvel de três períodos.</span></li><li><b>05</b><span><strong>Agregar pelo valor</strong>Pesos de 2022; cobertura publicada em cada resultado para garantir transparência.</span></li></ol></div><aside><span>DECISÃO METODOLÓGICA</span><h3>PST entra no índice, mas não é convertido arbitrariamente em kg.</h3><p>Uma peça pode ser uma viatura, uma máquina ou uma pequena mercadoria. A conversão fixa de 30 kg introduziria viés. Por isso, PST é calculado como preço por peça e integrado através do peso em valor.</p><div className="rule"><small>LIMITE SUPERIOR</small><b>300</b></div></aside></section>
<section id="gestao" className="section admin"><div><span className="kicker">GESTÃO E ACTUALIZAÇÃO</span><h2>Área reservada e publicação segura</h2><p>A base integral, o carregamento, a validação e o histórico ficam protegidos por perfis. O público recebe somente dados sem NUIT e nomes.</p></div><div className="roles"><article><b>Administrador</b><span>Utilizadores, perfis, regras e publicação</span></article><article><b>Gestor de dados</b><span>Carrega, corrige e processa ficheiros</span></article><article><b>Validador</b><span>Revê qualidade e aprova resultados</span></article><article><b>Analista</b><span>Consulta dados detalhados e exporta</span></article><article><b>Utilizador público</b><span>Consulta resultados publicados</span></article></div><DataManagement/></section>
<ComparisonPanel data={data}/><AnalyticsExpansion/><GeoTrade/>
<section className="section documents"><div className="section-head"><div><span className="kicker">DOCUMENTAÇÃO ACTUALIZADA</span><h2>Manual, relatório e apresentação</h2><p>Documentos consolidados com os cinco cenários, a balança comercial e o fluxo de actualização de dados.</p></div></div><div className="document-grid"><article><span>MANUAL</span><h3>Utilização e metodologia</h3><p>Guia do portal, filtros, cálculos, validação e gestão de dados.</p><div><a href="/downloads/Manual_Utilizacao_Metodologia_ICE_MZ_2026.pdf" download>PDF ↓</a><a href="/downloads/Manual_Utilizacao_Metodologia_ICE_MZ_2026.docx" download>Word ↓</a></div></article><article><span>RELATÓRIO FINAL</span><h3>ICE Moçambique 2022–2025</h3><p>Resultados, sensibilidade aos limites e balança comercial anual.</p><div><a href="/downloads/Relatorio_Final_ICE_Mocambique_2022_2025.pdf" download>PDF ↓</a><a href="/downloads/Relatorio_Final_ICE_Mocambique_2022_2025.docx" download>Word ↓</a></div></article><article><span>APRESENTAÇÃO</span><h3>Síntese para decisão</h3><p>Metodologia, evidência, decisões e roteiro de institucionalização.</p><div><a href="/downloads/Apresentacao_Final_ICE_Mocambique_2022_2025.pdf" download>PDF ↓</a><a href="/downloads/Apresentacao_Final_ICE_Mocambique_2022_2025.pptx" download>PowerPoint ↓</a></div></article></div></section>
<footer><div className="brand"><span>ME</span><div><b>REPÚBLICA DE MOÇAMBIQUE</b><small>MINISTÉRIO DA ECONOMIA · DNCE</small></div></div><p>Índice do Comércio Externo de Moçambique · Base 2022 = 100</p></footer></main>}
